name: Download and persist artifact

inputs:
  name:
    description: Artifact name prefix
    required: true
  arch:
    description: Architecture (X64 or ARM64)
    required: true
  os:
    description: Operating system (Linux or macOS)
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.name }}-${{ inputs.arch }}-${{ inputs.os }}
        path: cache-binary-${{ inputs.arch }}-${{ inputs.os }}
    - shell: bash
      run: cp ./cache-binary-${{ inputs.arch }}-${{ inputs.os }}/${{ inputs.name }} ./artifacts/${{ inputs.arch }}-${{ inputs.os }}
