name: Download and persist artifact

inputs:
  name:
    type: string
    required: true
  arch:
    type: choice
    options:
      - X64
      - ARM64
    required: true
  os:
    type: choice
    options:
      - Linux
      - macOS
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.name }}-${{ inputs.arch }}-${{ inputs.os }}
        path: cache-binary-${{ inputs.arch }}-${{ inputs.os }}
    - shell: bash
      run: cp ./cache-binary-${{ inputs.arch }}-${{ inputs.os }}/${{ inputs.name }} ./artifacts/${{ inputs.arch }}-${{ inputs.os }}
